name: Mirror AetrisVPN Configs

on:
  schedule:
    - cron: '*/30 * * * *'  # Запуск каждый час
  workflow_dispatch:     # Кнопка для ручного запуска

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download configs from Google Drive
        run: |
          curl -L "https://drive.usercontent.google.com/download?id=1uTVZsfiqGGzV5sLTjcoaf2cotQSQPSBg&export=download&confirm=t" -o AetrisVPN.txt

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@://github.com"
          git add AetrisVPN.txt
          git commit -m "Принудительное автообновление подписки" || true
          git pull --rebase origin main
          git push origin main
